[package]
name = "arbit"
version = "0.1.0"
authors = ["Zeb Barnett <me@zebbarnett.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = { version = "0.26.2" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde", "rustc-serialize"] }
uuid = { version = "1.1.2", features = ["serde"] }